/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React, { useState } from 'react';
import { generateWizardSuggestion } from '../services/orchestrator';
import { Prompt } from '../types';
import { Sparkles, ArrowRight, Check, Loader2, RefreshCw, MessageSquare } from 'lucide-react';

interface PromptWizardProps {
  onComplete: (prompt: Partial<Prompt>) => void;
  onCancel: () => void;
}

const PromptWizard: React.FC<PromptWizardProps> = ({ onComplete, onCancel }) => {
  const [step, setStep] = useState(0);
  const [loading, setLoading] = useState(false);
  const [input, setInput] = useState('');
  const [suggestion, setSuggestion] = useState<any>(null);

  const handleInitialIdea = async () => {
    if (!input.trim()) return;
    setLoading(true);
    try {
        const result = await generateWizardSuggestion(input);
        setSuggestion(result);
        setStep(1);
    } catch (e) {
        console.error(e);
    } finally {
        setLoading(false);
    }
  };

  const updateSuggestion = (key: string, value: string) => {
      setSuggestion((prev: any) => ({ ...prev, [key]: value }));
  };

  const finalize = () => {
     const newPrompt: Partial<Prompt> = {
         title: input.length > 30 ? input.substring(0, 30) + '...' : input,
         sfl: {
             field: { 
                 domain: suggestion.domain || 'General', 
                 process: suggestion.process || 'Thinking' 
             },
             tenor: { 
                 senderRole: suggestion.senderRole || 'Expert', 
                 receiverRole: suggestion.receiverRole || 'User', 
                 powerStatus: 'Equal', 
                 affect: (suggestion.affect || 'Professional') as any 
             },
             mode: { 
                 channel: 'Written', 
                 medium: 'Text', 
                 rhetoricalMode: (suggestion.rhetoricalMode || 'Descriptive') as any 
             }
         }
     };
     onComplete(newPrompt);
  };

  return (
    <div className="w-full bg-slate-900 rounded-xl overflow-hidden flex flex-col md:flex-row h-full min-h-[500px]">
       {/* Sidebar / Info Column */}
       <div className="md:w-1/3 bg-slate-950 border-r border-slate-800 p-6 flex flex-col">
           <div className="mb-6">
                <h3 className="font-bold text-slate-200 text-lg flex items-center gap-2 font-display mb-1">
                    <Sparkles className="w-5 h-5 text-primary-400" />
                    Wizard
                </h3>
                <p className="text-xs text-slate-500">AI-Assisted Prompt Construction</p>
           </div>
           
           <div className="space-y-4 flex-1">
               <div className={`p-4 rounded-lg border transition-all ${step === 0 ? 'bg-primary-900/10 border-primary-500/50' : 'bg-slate-900 border-slate-800 opacity-50'}`}>
                   <div className="w-6 h-6 rounded-full bg-slate-800 text-slate-400 flex items-center justify-center text-xs font-bold mb-2">1</div>
                   <h4 className="text-sm font-bold text-slate-200">Describe Intent</h4>
                   <p className="text-xs text-slate-500 mt-1">Tell us what you want to achieve in plain English.</p>
               </div>
               <div className={`p-4 rounded-lg border transition-all ${step === 1 ? 'bg-primary-900/10 border-primary-500/50' : 'bg-slate-900 border-slate-800 opacity-50'}`}>
                   <div className="w-6 h-6 rounded-full bg-slate-800 text-slate-400 flex items-center justify-center text-xs font-bold mb-2">2</div>
                   <h4 className="text-sm font-bold text-slate-200">Refine SFL</h4>
                   <p className="text-xs text-slate-500 mt-1">Adjust the linguistic parameters generated by the AI.</p>
               </div>
           </div>

           <button onClick={onCancel} className="mt-auto text-xs text-slate-500 hover:text-white transition-colors">Cancel Wizard</button>
       </div>

       {/* Main Content Area */}
       <div className="flex-1 p-6 md:p-8 overflow-y-auto">
           {step === 0 && (
               <div className="space-y-6 animate-in slide-in-from-right-4">
                   <div>
                       <label className="block text-slate-300 font-bold mb-3">What is your goal?</label>
                       <textarea 
                            value={input}
                            onChange={(e) => setInput(e.target.value)}
                            className="w-full h-48 bg-slate-800/50 border border-slate-700 rounded-xl p-4 text-slate-200 focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none resize-none placeholder:text-slate-600 transition-all text-base"
                            placeholder="Example: I need a prompt that acts like a senior Python developer reviewing junior code. It should be encouraging but strict on type safety."
                       />
                   </div>
                   
                   <div className="flex justify-end">
                       <button 
                         onClick={handleInitialIdea}
                         disabled={loading || !input.trim()}
                         className={`px-6 py-3 bg-gradient-to-r from-primary-600 to-indigo-600 hover:from-primary-500 hover:to-indigo-500 text-white rounded-xl flex items-center gap-2 font-bold transition-all shadow-lg ${loading || !input.trim() ? 'opacity-50 cursor-not-allowed' : 'hover:scale-105'}`}
                       >
                           {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <>Analyze Intent <ArrowRight className="w-5 h-5" /></>}
                       </button>
                   </div>
               </div>
           )}

           {step === 1 && suggestion && (
               <div className="space-y-8 animate-in slide-in-from-right-4">
                   <div className="bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                       <h5 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-2">
                           <MessageSquare className="w-3 h-3" /> Original Request
                       </h5>
                       <p className="text-sm text-slate-300 italic">"{input}"</p>
                   </div>
                   
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                       <div className="space-y-4">
                           <h4 className="text-xs font-bold text-accent-400 uppercase tracking-widest border-b border-accent-500/20 pb-1">Field (Subject)</h4>
                           <div className="space-y-1.5">
                               <label className="text-[10px] text-slate-500 uppercase font-bold">Domain</label>
                               <input value={suggestion.domain} onChange={e => updateSuggestion('domain', e.target.value)} className="w-full bg-slate-950 border border-slate-800 rounded px-3 py-2 text-sm text-slate-200 focus:border-primary-500 outline-none" />
                           </div>
                           <div className="space-y-1.5">
                               <label className="text-[10px] text-slate-500 uppercase font-bold">Process</label>
                               <input value={suggestion.process} onChange={e => updateSuggestion('process', e.target.value)} className="w-full bg-slate-950 border border-slate-800 rounded px-3 py-2 text-sm text-slate-200 focus:border-primary-500 outline-none" />
                           </div>
                       </div>

                       <div className="space-y-4">
                           <h4 className="text-xs font-bold text-primary-400 uppercase tracking-widest border-b border-primary-500/20 pb-1">Tenor (Tone)</h4>
                           <div className="space-y-1.5">
                               <label className="text-[10px] text-slate-500 uppercase font-bold">Sender Role</label>
                               <input value={suggestion.senderRole} onChange={e => updateSuggestion('senderRole', e.target.value)} className="w-full bg-slate-950 border border-slate-800 rounded px-3 py-2 text-sm text-slate-200 focus:border-primary-500 outline-none" />
                           </div>
                           <div className="space-y-1.5">
                               <label className="text-[10px] text-slate-500 uppercase font-bold">Affect</label>
                               <input value={suggestion.affect} onChange={e => updateSuggestion('affect', e.target.value)} className="w-full bg-slate-950 border border-slate-800 rounded px-3 py-2 text-sm text-slate-200 focus:border-primary-500 outline-none" />
                           </div>
                       </div>
                   </div>

                   <div className="flex justify-between items-center pt-6 border-t border-slate-800">
                       <button onClick={() => setStep(0)} className="text-slate-500 hover:text-white text-sm font-medium">Back</button>
                       <div className="flex gap-3">
                            <button onClick={handleInitialIdea} className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2">
                                <RefreshCw className="w-4 h-4" /> Regenerate
                            </button>
                            <button onClick={finalize} className="px-6 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg flex items-center gap-2 text-sm font-bold transition-all shadow-lg shadow-emerald-900/20 hover:scale-105">
                                <Check className="w-4 h-4" /> Create Project
                            </button>
                       </div>
                   </div>
               </div>
           )}
       </div>
    </div>
  );
};

export default PromptWizard;